### ISSUE TITLE
env-api v1 fallback

### ISSUE THREAD

**Issue by wincus** [InVisionApp/kit-deploymentizer#31]
hey @c1freitas ! Im trying to generate some manifests locally and I get the error: 
```bash
{ContainerRunStdout=service_name:"deploymentizer"}: [2017-01-30 14:27:28.767] [ERROR] [default] - Fallback not supported and/or wrong error code: 400
```

Is for a service that has not been migrated over yet ( mongoinit )

I think that env-api is returning 400 instead of 404 ( https://github.com/InVisionApp/kit-deploymentizer/blob/master/src/plugin/env-api-client-v3.js#L105 )

**Comment by c1freitas** [comment]
So do you want it to still generate the manifest?

**Comment by wincus** [comment]
yes ...

lol I might misunderstood how the integration would work. I thought deploymentizer would try v3 first and fallback to v1 ( or v2 ) if v3 was returning 4XX. That way we don't need to move the services all at the same time. Seems like Im missing something .... not sure what exactly :)

**Comment by c1freitas** [comment]
No, the env team said it would return a 404 if the file was not found. I am not sure why its returning a 400. I can check with them but we could update it to fall back with any 4XX code

**Comment by c1freitas** [comment]
I am closing this issue. The current solution is working for us. Any changes to manifest generation should include a redesign (or at least a reevaluation) of the workflow.
