### ISSUE TITLE
Change the mustache templates in kubernetes-coreos to support the new labels.

### ISSUE THREAD

**Issue by brianhall** [InVisionApp/kit-deploymentizer#43]
**Manifests: **(generated as: $service-deployment-$sha.yaml)
  metadata.name: $service-deployment-`{{{deployment.sha}}}`
  metadata.labels.state: live
  metadata.labels.sha:  `{{{deployment.sha}}}`
  metadata.labels.service: `{{{name}}}`
  selector.matchLabels.state: live

From: [Quick Rollbacks](https://invisionapp.quip.com/npgPANELpg94)

Start of PR: https://github.com/InVisionApp/kit-deploymentizer/issues/43

**Comment by c1freitas** [comment]
Note: These changes need to be **deployed** before #46.

**Comment by c1freitas** [comment]
The initial PR for this in CoreOS https://github.com/InVisionApp/kubernetes-coreos/pull/1913

If this looks good. We can start another PR off this to update all the other resource mustache templates as well any custom services.

@manute and @brianhall

**Comment by manute** [comment]
ok I am going to create the PR

**Comment by manute** [comment]
Are we going to update all resources or only for `projects`?

**Comment by c1freitas** [comment]
We want to update them all. The changes are backward compatible and this will allow us to switch any service to fastRollbacks with just an Astro change.

**Comment by manute** [comment]
oh nice.

**Comment by c1freitas** [comment]
This is also complete.
