### ISSUE TITLE
Update kit-deploymentizer to populate the new label values

### ISSUE THREAD

**Issue by brianhall** [InVisionApp/kit-deploymentizer#44]
From #43, deploymentizer should fill out these values.

From: [Quick Rollbacks](https://invisionapp.quip.com/npgPANELpg94)

**Comment by c1freitas** [comment]
This is waiting for approval of https://github.com/InVisionApp/kit-deploymentizer/pull/47. Once this is approved it will need to be added to kit-server.

**Comment by chesleybrown** [comment]
I think we can mark this as closed/completed now?
