### ISSUE TITLE
Cluster metadata should be available to templates

### ISSUE THREAD

**Issue by chrisfjones** [InVisionApp/kit-deploymentizer#86]
Currently only `cluster-var.yaml` is passed as context for templates. We should also include metadata from the `cluster.yaml`

Code reference:
https://github.com/InVisionApp/kit-deploymentizer/blob/master/src/lib/generator.js#L194

**Comment by c1freitas** [comment]
@erutherford pointed out that you have access to the cluster name via `$${METADATA_CLUSTER}`. Does this fit your need @arukaen

**Comment by arukaen** [comment]
@erutherford @c1freitas If my service had its own repo and was using `in-config` then yes `$${METADATA_CLUSTER}` would work but I am trying to avoid creating it as its own service because I want to avoid having to keep it updated with the upstream all the time.

**Comment by chrisfjones** [comment]
You can also fix the FROM reference to a specific digest like this:
`acme/app@sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`
which avoids pulling different versions unless you change the digest

**Comment by c1freitas** [comment]
closing, we have a workaround
